# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6754ced4cd505b1e51d75411f71198f5f18c1459f6de278fe3dfeb5905034c8bcc3b601b8fe0d356efd8e75cf50bddd294e5567ef886ebc15bdcdddfe84ab72e

test:
  secret_key_base: 1501361569e394c1eebe3454761a31fb0a56a9a09d6a1a53c32d3832540d70b70e2a115178c653941ded8271a3c9d7c42195ad450491d0d1695eeb46d0a0fa5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
